"""alterar tabela funcionarios

Revision ID: 3439fb7fa21c
Revises: aeb0ba4f3b67
Create Date: 2025-04-21 19:56:01.299027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3439fb7fa21c'
down_revision: Union[str, None] = 'aeb0ba4f3b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'cpf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('cpf', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
