"""alterar tabela funcionarios

Revision ID: aeb0ba4f3b67
Revises: 0507e1e05e75
Create Date: 2025-04-21 19:54:34.660546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb0ba4f3b67'
down_revision: Union[str, None] = '0507e1e05e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('cpf', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'cpf')
    # ### end Alembic commands ###
