"""criar tabela insumos

Revision ID: d5b2476e19a0
Revises: 3439fb7fa21c
Create Date: 2025-04-21 22:41:37.221265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b2476e19a0'
down_revision: Union[str, None] = '3439fb7fa21c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumos',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('funcionarios', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('funcionarios', 'funcao',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionarios', 'funcao',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('funcionarios', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_table('insumos')
    # ### end Alembic commands ###
